### PR TITLE
Configure mixpanel track api to use POST.

### PR DESCRIPTION
**Pull request by piyushcsiitd**
Current library only supports GET based http requests for /track calls, even though backend server side supports POST api as well. Due to a large number of properties, we are running into the URL length limits, breaking our collectors. So adding support to enable POST based /track calls.

https://github.com/mixpanel/mixpanel-js/issues/76

CC: @tdumitrescu

### CODE REVIEW

**Comment by piyushcsiitd** [comment]
@tdumitrescu Can you please review? (Or let me know how can i get this code approved)

Thanks

**Comment by tdumitrescu** [comment]
Yeah I'm hoping to publish early next week, but it's not top priority right now. It would help expedite the process if you could:
- remove the default function parameter (we don't transpile the lib source except for resolving imports, and it needs to run on older browsers)
- add a test case or two

Thanks!

**Comment by piyushcsiitd** [comment]
@tdumitrescu: 
1. I have removed the default parameter.
2. Regarding tests, I was thinking I can add a unit test around _send_request() in tests/test.js. Would that suffice?

Thanks & Regards

**Comment by piyushcsiitd** [comment]
@tdumitrescu Can you please provide clarification regarding the tests to add?

Thanks

**Comment by piyushcsiitd** [comment]
> Yeah I'm hoping to publish early next week, but it's not top priority right now. It would help expedite the process if you could:
> 
> * remove the default function parameter (we don't transpile the lib source except for resolving imports, and it needs to run on older browsers)
> * add a test case or two
> 
> Thanks!

Can you merge this? We are using custom build so far.

**Comment by tdumitrescu** [comment]
Did you ever manage to write any tests? There's nothing pushed here. Also can you get rid of the changes to package-lock.json?

**Comment by dnsorlov** [comment]
> Current library only supports GET based http requests for /track calls, even though backend server side supports POST api as well. Due to a large number of properties, we are running into the URL length limits, breaking our collectors. So adding support to enable POST based /track calls.
> 
> #76
> 
> CC: @tdumitrescu

Is there any official doc which can prove that Mixpanel supports POST from browsers?

**Comment by tdumitrescu** [comment]
Internal implementation ended up released in [v2.32.0](https://github.com/mixpanel/mixpanel-js/releases/tag/v2.32.0)

**Pull request closed without merging**
