### PR TITLE
Added option to disable automatic library injection

### PR DESCRIPTION
**Pull request by harmoney-nikr**
This is for instances where the developer would like to manually include the library themselves, eg as part of their tooling or bundled up along with their other concatenated dependencies.

### CODE REVIEW

**Comment by tdumitrescu** [comment]
Can I ask what build process you're using? There's really no advantage to using the snippet-based loader except to load the full lib asynchronously. For bundled synchronous loading, we have builds available that will work with Browserify, Webpack, JSPM, etc.

**Comment by harmoney-nikr** [comment]
Those builds aren't made available as a the bower module. If they were then they would solve the issue; https://github.com/kuhnza/angular-mixpanel can use one of those instead and this PR is moot.

**Comment by tdumitrescu** [comment]
Are you sure you're getting the latest version of the lib (2.7.1) from Bower? The module-based builds should be under `bower_components/mixpanel/build/`.

**Comment by harmoney-nikr** [comment]
Thanks @tdumitrescu, it's there now. I think it was a cached version or something finicky with bower dependencies that I hadn't noticed. Sorry for the false alarm; I can use one of these builds to submit a PR to `angular-mixpanel`.

**Comment by tdumitrescu** [comment]
Awesome, glad we could sort it out.

**Pull request closed without merging**
