### PR TITLE
unify .register syntax, add actionable date example in JS

### PR DESCRIPTION
**Pull request by robertott**

### CODE REVIEW

**Comment by arittr** [comment]
FWIW I think all the quotes in the documentation / comments should be double (") not single (') - do you think it would be a lot of work to change all the instances of this? might be nice to have some consistency

**Comment by arittr** [comment]
at least let's make your change use double qs

**Comment by Suhail** [comment]
You should use single quotes since a majority of the code utilizes single quotes. Consistency is the primary purpose of choosing between single vs. double in JS.

**Comment by arittr** [comment]
overruled by SDK owner.... so LGTM!

**Comment by zakj** [comment]
LGTM, though I'm holding off in case you want to change your whitespace here before I merge. If you do, that'd be a great time to practice your rebase-and-squash git-fu!

**Comment by zakj** [comment]
merged as squashed 0c02bff

**Pull request closed without merging**
