### PR TITLE
Support for CommonJS, AMD, UMD, and ES6 modules

### PR DESCRIPTION
**Pull request by tdumitrescu**
built from ES6 source

the long-delayed fix for https://github.com/mixpanel/mixpanel-js/issues/2

### CODE REVIEW

**Comment by bmcorser** [comment]
:+1:

**Comment by KeKs0r** [comment]
Tested it in my current app and works like a charm.

**Comment by tdumitrescu** [comment]
Hi @KeKs0r, thanks so much for the testing and reports, it's super useful - I missed it for a while because GitHub doesn't seem to send notifications for comment updates, just new comments.

The first issue stems from enabling strict mode, automatically added when transpiling from ES6 modules (part of the spec). We should be able to fix that error.

Likewise, shouldn't have switched anything to ES6 syntax except the module code; the bundling via esperanto doesn't actually transpile anything else.

Anyway, this PR has gotten quite a bit behind master and has conflicts; I'll post back here when it's updated.

**Comment by tdumitrescu** [comment]
@KeKs0r I've pushed up a new version of this branch; the two issues mentioned in your comment should be resolved now, and it's up to date with master.

@evnp @zakj @mp-andrew if you have any opinions on this approach, feel free to chime in.

**Comment by oncletom** [comment]
Why not using ES6 modules directly and compiling to UMD or whatsoever using Babel?

**Comment by tdumitrescu** [comment]
This does use ES6 modules directly. And compiles to AMD/UMD/CJS with Rollup, because Babel doesn't bundle.

**Comment by oncletom** [comment]
Okay awesome @tdumitrescu! I did not know about Rollup :-)

Can't wait for this PR to be merged, I would love to use it in a browserified project of ours.

**Comment by tdumitrescu** [comment]
Can't wait either. I think we're real close now, it's been through a few rounds of review and I'm holding off on pushing anything else to master until this lands.

**Comment by oncletom** [comment]
:+1:

**Comment by bmcorser** [comment]
:rainbow: :racehorse: We move towards a brighter JavaScript future together.

**Comment by oncletom** [comment]
\o/ yay, thanks a lot :-)

**Pull request merged**
