### PR TITLE
add localStorage support

### PR DESCRIPTION
**Pull request by sandorfr**
Add localStorage as an alternative to cookies to enable scenarios such as cordova support:
* Add _.localStorage which shares the same 'api' as _.cookie
* Add storage option which accepts 'localStorage' option
* Replace direct reference to _.cookie to use the current storage.
See #24 for more informations

### CODE REVIEW

**Comment by tdumitrescu** [comment]
Awesome, thanks so much for doing this. The code looks very much like what I was hoping for - a simple drop-in using the same API for cookies and localStorage. We're going to do a little cleanup over here before releasing, mainly hardening the error-handling:
- add unit tests for alternative storage
- undo changes to minified snippets, since the snippet code hasn't changed (maybe a closure compiler version difference?)
- (optional?) fallback to cookies if localStorage fails/doesn't exist
- exception-handling for storage failure cases (so it doesn't blow up anyone's app on older browsers etc)

I wouldn't worry about the exception-handling/fallback stuff, but if you want to add the first two (esp. unit tests) that would be helpful in expediting this change.

**Comment by sandorfr** [comment]
I fixed my commit to remove unwanted changes. In addition I added a check to ensure that localStorage is actually available and fallback to cookie if not.

Regarding unit test I seems that current MixpanelCookie class is not tested independently of mixpanel lib implementation. I would gladly help but I must say It is not easy to jump in :)

**Comment by tdumitrescu** [comment]
Thanks, no worries about the tests, we'll take care of it. Probably won't be able to get to this before next week, thanks for your patience!

**Comment by tdumitrescu** [comment]
Hi, just wanted to check in and let you know I haven't forgotten about this. We have a private version of this branch with unit tests and some extra fixes almost ready to go. With fundamental changes like this we like to run the dev version for a while on mixpanel.com before releasing publicly, so it won't land on master right away, but rest assured it's on the way!

**Comment by sandorfr** [comment]
Great news :) Thanks

**Comment by tdumitrescu** [comment]
Hi @sandorfr, thanks again for the patch, which has been released in v2.5.0. As you can see in the git history (https://github.com/mixpanel/mixpanel-js/compare/7be2439635a0fbb36ec2db8e9264781828d46928...5ef1be42b40eda9dd2ab5ffb4ca84702583d8adf), a lot's been added on top of your initial commits - mainly centered around testing, dealing with exception conditions we've seen while running this code on mixpanel.com (e.g., browser extensions preventing localStorage access), and updating naming conventions.

You'll want to note that your config option is now called `persistence` instead of `storage`, but otherwise everything's compatible with your version.

**Comment by sandorfr** [comment]
Awesome, I'm going to update my blog post and integrate this in my app very soon.

**Pull request merged**
