### PR TITLE
Implement `mixpanel.people.union`

### PR DESCRIPTION
**Pull request by mogstad**

### CODE REVIEW

**Comment by mchambaud** [comment]
Will this be merged anytime soon?

**Comment by tdumitrescu** [comment]
Hey, sorry about the delay! We've got a cleaned-up version ready internally, will get it out next week in v2.4.

**Comment by mchambaud** [comment]
Great! Looking forward to it!

**Comment by tdumitrescu** [comment]
Now released in v2.4.0 (note that you'll need to update the embed code to use people.union, see https://mixpanel.com/help/reference/javascript).

**Comment by mchambaud** [comment]
Awesome, will try that tomorrow!

**Pull request closed without merging**
