### PR TITLE
check for either meta-click or ctrl-click in LinkTracker before preventDefault

### PR DESCRIPTION
**Pull request by tdumitrescu**
quick fix for https://github.com/mixpanel/mixpanel-js/issues/20

### CODE REVIEW

**Comment by malectro** [comment]
looks good. have we tested on linux (the offending OS)?

**Comment by tdumitrescu** [comment]
Yeah I checked on ubuntu and windows

**Comment by pfhayes** [comment]
Does this affect ctrl-click on OS X? On that platform, ctrl-click opens the context menu (same as right click).

I don't think meta-click does anything on Windows/Ubuntu so that case is probably fine.

**Comment by tdumitrescu** [comment]
As far as I could see in manual QA, osx ctrl-click is unaffected - it actually doesn't fire the element's normal event handlers at all when opening the context menu (at least in chrome)...

**Comment by pfhayes** [comment]
Cool! Thanks for confirming

**Pull request merged**
