### PR TITLE
cross-env version of UUID() Cypress-stalling fix

### PR DESCRIPTION
**Pull request by tdumitrescu**
Based on https://github.com/mixpanel/mixpanel-js/pull/368

### CODE REVIEW

**Comment by adrianherd** [comment]
Im having trouble build the distrubution on my end, but this looks like a should work? 😄

**Comment by tdumitrescu** [comment]
Interesting @adrianherd, it should be the same build process that you used for developing https://github.com/mixpanel/mixpanel-js/pull/368. But we're cutting a release this week anyway, so I'll include this branch and if the new version has any issues for you we can follow up again.

**Comment by adrianherd** [comment]
I was just editing my node_modules directly for that... 😬 

Anyways! got the build to work by removing the `pushd` example stuff from the `build.sh`. Copy pasted the dist folder into my node_modules and built cypress with the newer distribution.

Can confirm that this works and doesn't break our tests anymore :)

**Comment by adrianherd** [comment]
closed my pull request in favor of this version 👍🏼

**Pull request merged**
